// After `next build`: write out/sw.js that precaches every file in the export,
// so the app opens with no signal after the first visit. New build = new cache version.
import { readdirSync, statSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { createHash } from "node:crypto";

const OUT = "out";
const files = [];
(function walk(dir) {
  for (const f of readdirSync(dir)) {
    const p = join(dir, f);
    if (statSync(p).isDirectory()) walk(p);
    else if (!/\.map$/.test(f) && f !== "sw.js" && f !== ".nojekyll") files.push(relative(OUT, p).split("\\").join("/"));
  }
})(OUT);
const hash = createHash("sha1");
for (const f of files.sort()) hash.update(f).update(readFileSync(join(OUT, f)));
const version = hash.digest("hex").slice(0, 10);
// index.html files are cached under their folder URL too ("history/" as well as "history/index.html")
const urls = files.flatMap(f => (f.endsWith("index.html") ? [f, f.slice(0, -"index.html".length)] : [f]));

const sw = `// Generated by scripts/gen-sw.mjs. Do not edit.
const CACHE = "lift-log-${version}";
const URLS = ${JSON.stringify(urls)};
const scope = self.registration.scope;
self.addEventListener("install", e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(URLS.map(u => new URL(u, scope).href))).then(() => self.skipWaiting()));
});
self.addEventListener("activate", e => {
  e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k.startsWith("lift-log-") && k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener("fetch", e => {
  const req = e.request;
  if (req.method !== "GET" || !req.url.startsWith(scope)) return;
  if (req.mode === "navigate") {
    // Network first so updates show up; cached page when offline
    e.respondWith(fetch(req).then(r => { const copy = r.clone(); caches.open(CACHE).then(c => c.put(req, copy)); return r; })
      .catch(() => caches.match(req, { ignoreSearch: true }).then(r => r || caches.match(new URL("./", scope).href))));
    return;
  }
  e.respondWith(caches.match(req, { ignoreSearch: true }).then(r => r || fetch(req)));
});
`;
writeFileSync(join(OUT, "sw.js"), sw);
console.log(`sw.js: ${urls.length} URLs, cache lift-log-${version}`);
